from sqlalchemy import create_engine, update
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship
from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, Date
from datetime import datetime
import operator


engine = create_engine('sqlite:///database\\mydb.db')
Session = sessionmaker(bind=engine)
session = Session()
Base = declarative_base()


class Member(Base):
    """
    Table that holds information about club members
    """
    __tablename__ = "member"

    memberID = Column(Integer, primary_key=True)
    first_name = Column(String(50), nullable=False)
    last_name = Column(String(50), nullable=False)
    join_date = Column(Date, nullable=False)
    due_fee = Column(Boolean, nullable=False)
    # A one to many relationship where a person can have many registered addresses
    # When a member is deleted all the related addresses are deleted as well
    address = relationship("Address", backref="member", cascade='all,delete-orphan')

    # if you want to add the example members uncomment this ↓
    # def __init__(self, first_name, last_name, join_date, due_fee):
    #     self.first_name = first_name
    #     self.last_name = last_name
    #     self.join_date = join_date
    #     self.due_fee = due_fee
        
    def __repr__(self):
        return f"{self.first_name} {self.last_name} {self.join_date} {self.due_fee}"
    

class Address(Base):
    __tablename__ = "address"
    addressID = Column(Integer, primary_key=True)
    gata = Column(String(100), nullable=False)
    postnummer = Column(String(6), nullable=False)
    postort = Column(String(50), nullable=False)
    memberID = Column(Integer, ForeignKey('member.memberID'), nullable=False)
    
    # if you want to add the example members uncomment this ↓
    # def __init__(self, gata, postnummer, postort, member):
    #     self.gata = gata
    #     self.postnummer = postnummer
    #     self.postort = postort
    #     self.member = member
        
    def __repr__(self):
        """
        Used in the manner {member5.address} to display which adresses
        that are registered on the selected member in the app
        """
        return f"{self.gata} \n {self.postnummer}, {self.postort}\n"
    


Base.metadata.create_all(engine)


class Club():
    """
    The Club class administers the database actions related to the app.
    Attempting to separate the database actions from the ones generated by the app (e.g. values['-TABLE-']) 
    """
    
    @staticmethod
    def CreateDB():
        Base.metadata.create_all(engine)
    
    @staticmethod    
    def Select():
        return session.query(Member).all()
    
    @staticmethod
    def get_member(memberID):
        """
        Gets a member object from the Member table
        memberID = the first value (index 0) of the selected row in the currently displayed table
        """
        member = session.query(Member).get(memberID)
        print(member.address)
        return member
      
    @staticmethod
    def create_table_list(members):
        """
        The table element only accepts a list so the database query is converted to a list of lists
        The due_fee bool is converted from False to 'Ej Betald' and from True to 'Betald'
        """
        memberList = []
        for member in members:
            if member.due_fee:
                due_fee = "Ej Betald"
            else:
                due_fee = "Betald"
            member_parsed = [member.memberID, member.first_name, member.last_name, member.join_date, due_fee]
            memberList.append(member_parsed)         
        return memberList
    
    @staticmethod
    def search_by_id(memberID):
        """ 
        Used the get method to the selected users which is then converted to a nested list.
        
        memberID = the first value (index 0) of the selected row in the currently displayed table
        """   
        # Every time a member is retrieved from the database the due_fee has to be converted     
        member_query = session.query(Member).get(memberID)
        if member_query.due_fee:
            due_fee = "Ej Betald"
        else:
            due_fee = "Betald"
        member = [[member_query.memberID, member_query.first_name, member_query.last_name, member_query.join_date, due_fee]]
        return member
    
    
    @staticmethod
    def search_by_name(memberName):
        """ 
        filter by the input name in the Members table, then converted to a nested list.
        
        memberName = the second value (index 1) of the selected row in the currently displayed table
        """  
        members = session.query(Member).filter_by(first_name = memberName)    
        return Club.create_table_list(members)
   
    @staticmethod
    def Insert(form_data):
        """
        Uses the values from the input form (i.e. values['-TABLE-']),
        and assigns those values to an insert statement that gets added to the database.
        form_data = the relevant values from form tab in the app.
        """
        insert_stmt_Member = Member(first_name=form_data[0], 
                            last_name=form_data[1], 
                            join_date=form_data[2],
                            due_fee =form_data[3])
        session.add(insert_stmt_Member)
        session.commit()
        
        # To get the foreign key for the Address table insert statement,
        # we query for the highest memberID (which is the newest member)
        newest_member = session.query(Member).order_by(Member.memberID.desc()).first()
        
        insert_stmt_Address = Address(
                                    gata=form_data[4], 
                                    postnummer=form_data[5], 
                                    postort=form_data[6],
                                    member=newest_member)
        session.add(insert_stmt_Address)
        session.commit()
    
    @staticmethod
    def Delete(memberID):
        # if we use delete_stmt = delete(Member).where(Member.memberID == memberID) cascade doesnt apply
        user = session.query(Member).filter(Member.memberID == memberID).one()
        session.delete(user)
        session.commit()      
    
    @staticmethod
    def insert_only_address(form_address):
        """
        Used when adding another address for an existing member
        """
        # find all the addresses in the register that matches what was put in the from 
        address_lookup = session.query(Address).filter(Address.gata==form_address[0], Address.postnummer==form_address[1],
                                   Address.postort==form_address[2]).all()
        
        # loops through all addresses and appends all the members that live there
        all_matching_addresses = []
        for member in address_lookup:
            print(member.member.memberID)
            all_matching_addresses.append(member.member.memberID)
        
        # checks if the current member is already registered on this address
        # if a match is found, an error message is given (via popup) and nothing happens
        if form_address[3] in all_matching_addresses:
            found_match = True
        
        # The address is not used by the member and it is thus added as usual
        else:
            member_query = session.query(Member).get(form_address[3])
            insert_stmt_Address = Address(
                            gata=form_address[0], 
                            postnummer=form_address[1], 
                            postort=form_address[2],
                            member=member_query)
            session.add(insert_stmt_Address)
            session.commit()
            found_match = False
            
        # returns a bool that is used to decide which popup to show
        return found_match
        
    
    @staticmethod
    def format_address(member_address):
        """
        Used together with the Address __repr__ format the address info
        """
        
        # To get rid of the brackets from the list
        addressString = str(member_address.address)
        addressString_without_brackets = addressString[1:-1]
        return addressString_without_brackets
    
    @staticmethod
    def change_due_date(member, due_fee):
        """
        Change due date in database for the selected member.
        member = selected memberID
        due_fee = due_fee in converted to swedish string format
        """
        
        if due_fee == "Betald":
            klubbavgift = True  # before False
        
        elif due_fee == "Ej Betald":
            klubbavgift = False # before True
        
        
        update_stmt = update(Member).values(due_fee=klubbavgift).where(Member.memberID == member)
        session.execute(update_stmt)
        session.commit()
    
    @staticmethod    
    def sort_table(table, column):
        """
        Sorts the current table according to the key from operator module
        which column to sort by is the clicked table event
        """
        
        table = sorted(table, key=operator.itemgetter(column))
        return table

    
 # if Anders wnat to speed up the testing of the datbase/app ↓ ↓ ↓

# m1 = Member("Magnus", "Jensen", datetime.now(), False)
# m2 = Member("Erik", "Eriksson", datetime.now(), True)
# m3 = Member("Anders", "Andersson", datetime.now(), False)
# m4 = Member("Victor", "Victorsson", datetime.now(), False)
# m5 = Member("Andersson", "Silva", datetime.now(), True)
# m6 = Member("BJ", "Pen", datetime.now(), False)
# m7 = Member("Brock", "Lesnar", datetime.now(), True)
# m8 = Member("Chuck", "Lidell", datetime.now(), False)
# m9 = Member("Chuck", "Norris", datetime.now(), True)
# m10 = Member("Sylvester", "Stalone", datetime.now(), True)
# m11 = Member("Testperson", "TEST_TEST", datetime.now(), False)


# session.add(m1)
# session.add(m2)
# session.add(m3)
# session.add(m4)
# session.add(m5)
# session.add(m6)
# session.add(m7)
# session.add(m8)
# session.add(m9)
# session.add(m10)
# session.add(m11)
# session.commit()

# a1 = Address("Lilla Sällskapets väg 5", "127 55", "Skärholmen",m1)
# a2 = Address("Svängvägen 35", "141 41", "Huddinge",m2)
# a3 = Address("Rolig väg 12", "121 21", "minKommun", m3)
# a4 = Address("Rolig väg 12", "121 21", "minKommun", m4)
# a5 = Address("Brazil Street", "333 33", "Brazil Commune", m5)
# a6 = Address("Fight Street", "444 44", "Fight Land", m6)
# a7 = Address("Weird Street", "461 11", "Weird World", m7)
# a8 = Address("Evil Place", "445 55", "Dark World", m8)
# a9 = Address("Happy Street", "987 42", "Lots of Drugs", m9)
# a10 = Address("Unknown Street", "674 44", "Strange Place Indeed", m10)
# a11 = Address("Second Street 5", "777 89", "Lake Place", m1)
# a12 = Address("Makeup Street", "734 22", "Sunset bullet", m11)

# session.add(a1)
# session.add(a2)
# session.add(a3)
# session.add(a4)
# session.add(a5)
# session.add(a6)
# session.add(a7)
# session.add(a8)
# session.add(a9)
# session.add(a10)
# session.add(a11)
# session.add(a12)
# session.commit()